### ISSUE TITLE
拿着别人开源的东西来卖钱，你不觉得羞耻吗？

### ISSUE THREAD

**Issue by wuzhihui04** [hcjsky/listen1-and#1]

**Comment by hcjsky** [comment]
首先插件版本是MIT协议的。其次编译修改chromium非常复杂，光下载代码就需要开通谷歌服务器下载一天，然后从服务器再回传到国内电脑编译修改，而且修改调试让浏览器直接运行插件非常难。并且移动端界面适配也是我花费了很多时间修改的，这都付出很多时间和精力的了。而且如果不收费，这个软件广泛流传，人家公司起诉就更麻烦了。

**Comment by hcjsky** [comment]
如果有想让浏览器插件变成独立应用的欢迎找我商务合作:)

**Comment by laughingchs** [comment]
而且这收费相对国内来说还挺夸张的，5元/年，用的人多点给维护者一点捐赠也行，但几十有点夸张了。。。

**Comment by hcjsky** [comment]
鉴于没人付费，只好免费了加捐赠了

**Comment by wuzhihui04** [comment]
首先，表示抱歉，对于开源的认知并不全面。其次，表示对免费加捐赠的支持，刚捐赠了，能力有限，一点对开发者的支持。
